# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='liner',
    version='0.1.0',
    description='Generate a fingerprint for your source code.',
    python_requires='==3.*,>=3.7.0',
    author='finnkauski',
    author_email='iwiivi@gmail.com',
    license='MIT',
    entry_points={"console_scripts": ["liner = liner:main"]},
    packages=['liner'],
    package_dir={"": "."},
    package_data={},
    install_requires=['click==7.*,>=7.0.0', 'matplotlib==3.*,>=3.1.3'],
)
